autoload -U compinit
compinit

zstyle ':completion:*' menu select
setopt list_packed

# alias
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -l'
alias lla='ls -la'
alias c='cat'
alias d='diff'
alias f='free -m'
alias l='less'
alias q='exit'
alias s='TERM=screen screen'
alias sc='TERM=screen screen -c .screenrc'
alias t='tmux'

alias g='git'
alias b='bundle'
alias be='bundle exec'
alias bi='bundle install'
alias bu='bundle update'
alias r='rails'
alias dok='docker'
alias doki='docker image'
alias dokc='docker container'
alias dokv='docker volume'
alias dokn='docker network'
alias dokco='docker-compose'
alias ku='kubectl'
alias m='make'
alias tf='terraform'
alias awsd='docker run -e AWS_PROFILE=$AWS_PROFILE --rm -it -v ~/.aws:/root/.aws amazon/aws-cli'

if [ -f "$HOME/.zsh_os" ]; then
  . "$HOME/.zsh_os"
fi

if [ -f "$HOME/.zsh_local" ]; then
  . "$HOME/.zsh_local"
fi

autoload -Uz vcs_info
precmd_vcs_info() { vcs_info }
precmd_functions+=( precmd_vcs_info )
setopt prompt_subst
zstyle ':vcs_info:git:*' check-for-changes true
zstyle ':vcs_info:git:*' stagedstr "%F{yellow}!"
zstyle ':vcs_info:git:*' unstagedstr "%F{red}+"
zstyle ':vcs_info:*' formats "%F{green}%c%u[%b]%f"
zstyle ':vcs_info:*' actionformats '[%b|%a]'

PROMPT='%F{cyan}%n@%m%f: [%~] $vcs_info_msg_0_ %# '

HISTFILE=~/.zsh_history
SAVEHIST=100000 # file
HISTSIZE=1000   # memory

setopt APPEND_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_NO_STORE
setopt HIST_REDUCE_BLANKS
setopt SHARE_HISTORY

bindkey -e
bindkey '\e[3~' delete-char
bindkey '^R' history-incremental-search-backward

