if [ -f /etc/bash_completion ]; then
  . /etc/bash_completion
fi

if [ -f "$HOME/.bash_minimum" ]; then
  . "$HOME/.bash_minimum"
fi

if [ -f "$HOME/.bash_os" ]; then
  . "$HOME/.bash_os"
fi

if [ -f "/usr/local/bin/rbenv" ]; then
  eval "$(rbenv init -)"
  . /usr/local/Cellar/rbenv/0.2.1/completions/rbenv.bash
fi
