" width
set lines=54
" height
set columns=193

" show gui tab always
set showtabline=2

" color
set background=light
colorscheme solarized

" font
set guifont=Consolas:h12

" no tool bar
set guioptions-=T

" no menu bar
set guioptions-=m

" no right scroll bar
set guioptions-=r
set guioptions-=R

" no left scroll bar
set guioptions-=l
set guioptions-=

" no bottom scroll bar
set guioptions-=b

" for unite.vim
let g:unite_enable_start_insert=1
noremap <C-P> :Unite buffer<CR>
noremap <C-N> :Unite -buffer-name=file file<CR>
noremap <C-Z> :Unite file_mru<CR>
au FileType unite nnoremap <silent> <buffer> <expr> <C-j> unite#do_action('split')
au FileType unite inoremap <silent> <buffer> <expr> <C-j> unite#do_action('split')
au FileType unite nnoremap <silent> <buffer> <expr> <C-l> unite#do_action('vsplit')
au FileType unite inoremap <silent> <buffer> <expr> <C-l> unite#do_action('vsplit')
au FileType unite nnoremap <silent> <buffer> <ESC><ESC> :q<CR>
au FileType unite inoremap <silent> <buffer> <ESC><ESC> <ESC>:q<CR>
