" compatibility
set nocompatible

" file type
filetype off

" for vundle
set rtp+=~/.vim/vundle/
call vundle#rc()
Bundle 'unite.vim'
Bundle 'Solarized'
Bundle 'Flex-Development-Support'

" file type again
filetype plugin indent on

" hilight
syntax enable 

" tab
set tabstop=2
set shiftwidth=2 " indent width when cindent or autoindent called
set softtabstop=0 " 0 is same with tabstop
set expandtab

" indent
set autoindent
set smartindent

au BufNewFile,BufRead *.as set filetype=actionscript 
" au BufNewFile,BufRead *.mxml set filetype=mxml

" input
set backspace=indent,eol,start
set formatoptions=lmoq " add multibyte

" supplementation
inoremap { {}<LEFT>
inoremap [ []<LEFT>
inoremap ( ()<LEFT>
inoremap " ""<LEFT>
inoremap ' ''<LEFT>

" search
set wrapscan
set ignorecase
set smartcase
set incsearch
set hlsearch
nmap <Tab><Tab> :nohlsearch<CR><ESC> " delete search hilight hit tab key twice 

" file
set nobackup
set autoread
set noswapfile
set hidden

" display
set showmatch
set showcmd
set showmode
set number
set wrap
set list
set listchars=tab:>\
set notitle
set scrolloff=5

" status line
set laststatus=2

" mouse
set mouse=a
set ttymouse=xterm2
map m :set mouse=a<CR>
map mm :set mouse=<CR>
